version: '3'
services:
  nextjs-gestion:
    image: nextjs-gestion:latest # Puedes cambiar esto a la imagen de Docker que estés usando
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev # Comando para correr la app en modo desarrollo
